add_test([=[QddTest.ArithmeticTest]=]  /home/swli0426/Code/QDD/test/test/qdd_test [==[--gtest_filter=QddTest.ArithmeticTest]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[QddTest.ArithmeticTest]=]  PROPERTIES WORKING_DIRECTORY /home/swli0426/Code/QDD/test/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[QddTest.CircuitTest]=]  /home/swli0426/Code/QDD/test/test/qdd_test [==[--gtest_filter=QddTest.CircuitTest]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[QddTest.CircuitTest]=]  PROPERTIES WORKING_DIRECTORY /home/swli0426/Code/QDD/test/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[QddTest.GroverTest]=]  /home/swli0426/Code/QDD/test/test/qdd_test [==[--gtest_filter=QddTest.GroverTest]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[QddTest.GroverTest]=]  PROPERTIES WORKING_DIRECTORY /home/swli0426/Code/QDD/test/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[QddTest.QFTTest]=]  /home/swli0426/Code/QDD/test/test/qdd_test [==[--gtest_filter=QddTest.QFTTest]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[QddTest.QFTTest]=]  PROPERTIES WORKING_DIRECTORY /home/swli0426/Code/QDD/test/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  qdd_test_TESTS QddTest.ArithmeticTest QddTest.CircuitTest QddTest.GroverTest QddTest.QFTTest)
