name: Publish to PyPI

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: {}

jobs:
  build_wheels:
    name: Build wheels (${{ matrix.os }} ${{ matrix.arch }} / cp${{ matrix.python-tag }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
        python-tag: ["39", "310", "311", "312", "313"]
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: ubuntu-24.04-arm
            arch: aarch64
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pypa/cibuildwheel@v3.3.0
        env:
          CIBW_ARCHS_LINUX: ${{ matrix.arch }}
          CIBW_BUILD: cp${{ matrix.python-tag }}-manylinux_${{ matrix.arch }}
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.arch }}-cp${{ matrix.python-tag }}
          path: ./wheelhouse/*.whl

  build_sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
      - run: pipx run build --sdist
      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz

  publish-to-pypi:
    needs: [build_wheels, build_sdist]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/qdd
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist/
          pattern: "wheels-*"
          merge-multiple: true
      - uses: actions/download-artifact@v4
        with:
          path: dist/
          name: sdist
      - run: ls -la dist/
      - uses: pypa/gh-action-pypi-publish@release/v1
